{"timestamp":"2025-09-16T22:12:32.781684","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-16T22:12:32.784722","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/oews_onet_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-16T22:12:36.274263Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-16T22:12:36.275635Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-16T22:12:36.276210Z","level":"info","event":"Current task name:oews_extract","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-16T22:12:36.276773Z","level":"info","event":"Dag name:oews_onet_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-16T22:12:44.358326","level":"warning","event":"Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f861ab91ca0>: Failed to resolve 'selenium' ([Errno -2] Name or service not known)\")': /wd/hub/session","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-16T22:12:48.347718","level":"warning","event":"Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f861ab595e0>: Failed to resolve 'selenium' ([Errno -2] Name or service not known)\")': /wd/hub/session","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-16T22:12:52.314840","level":"warning","event":"Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f861ab91fa0>: Failed to resolve 'selenium' ([Errno -2] Name or service not known)\")': /wd/hub/session","logger":"urllib3.connectionpool"}
{"timestamp":"2025-09-16T22:12:56.300340","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"MaxRetryError","exc_value":"HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f861ab91bb0>: Failed to resolve 'selenium' ([Errno -2] Name or service not known)\"))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/pipeline/load_data.py","lineno":258,"name":"extract_oews_data"},{"filename":"/opt/airflow/pipeline/load_data.py","lineno":27,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py","lineno":212,"name":"__init__"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py","lineno":299,"name":"start_session"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py","lineno":352,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py","lineno":302,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/remote_connection.py","lineno":322,"name":"_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py","lineno":143,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/_request_methods.py","lineno":278,"name":"request_encode_body"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/poolmanager.py","lineno":459,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":871,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"NameResolutionError","exc_value":"<urllib3.connection.HTTPConnection object at 0x7f861ab91bb0>: Failed to resolve 'selenium' ([Errno -2] Name or service not known)","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":493,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":494,"name":"request"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1333,"name":"endheaders"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1093,"name":"_send_output"},{"filename":"/usr/local/lib/python3.12/http/client.py","lineno":1037,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":325,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":205,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"gaierror","exc_value":"[Errno -2] Name or service not known","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":60,"name":"create_connection"},{"filename":"/usr/local/lib/python3.12/socket.py","lineno":978,"name":"getaddrinfo"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-16T22:12:56.319377Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-16T22:12:56.320038Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-16T22:12:56.320451Z","level":"info","event":"Task:<Task(PythonOperator): oews_extract>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-16T22:12:56.320806Z","level":"info","event":"Failure caused by HTTPConnectionPool(host='selenium', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f861ab91bb0>: Failed to resolve 'selenium' ([Errno -2] Name or service not known)\"))","chan":"stdout","logger":"task"}
